#!/bin/sh
git archive --prefix=otp_src/ -o scripts/otp_src.tar.gz HEAD
docker build -f scripts/Dockerfile.pack-otp -t otp-src scripts
rm scripts/otp_src.tar.gz
docker build -f scripts/Dockerfile.run-tests -t otp-run-tests scripts
