FROM ubuntu:16.04

RUN apt-get update && apt-get --fix-missing -y install build-essential m4 libncurses5-dev libssh-dev unixodbc-dev libgmp3-dev fop xsltproc default-jdk git autoconf libwxbase3.0-dev libwxgtk3.0-dev

RUN mkdir /daily_build
WORKDIR /daily_build

ADD otp_src.tar.gz /daily_build
